micronaut:
  server:
    port: 8081
    cors:
      enabled: true
      port: 8081
      netty:
        worker:
          event-loop-group: other
          dual-protocol: true
  netty:
    event-loops:
      other:
        num-threads: 8
  application:
    name: framer
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
    versioning:
      enabled: true
netty:
  default:
    allocator:
      max-order: 3
#endpoints:
#  health:
#    enabled: true
#    sensitive: false
#    details-visible: ANONYMOUS
#  info:
#    enabled: true
#    sensitive: false
#  routes:
#    enabled: true
#    sensitive: true
